# scraper.py
from dotenv import load_dotenv
load_dotenv()

import requests
from bs4 import BeautifulSoup
from app import create_app, db
from models import Release
from datetime import datetime
import urllib3 # <-- NEW IMPORT

# --- NEW: Disable the warning that will be generated by verify=False ---
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
# --- END OF NEW SECTION ---


def scrape_drop_date_api():
    """Fetches upcoming releases directly from TheDropDate's internal API."""

    app = create_app()
    with app.app_context():
        URL = "https://api.thedropdate.com/v2/products?filter[release_type]=coming_soon&sort=release_date&page[size]=50"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

        try:
            print(f"Requesting data from internal API: {URL}")
            # --- MODIFIED: Added verify=False to bypass SSL issue ---
            response = requests.get(URL, headers=headers, verify=False)

            response.raise_for_status()
            print("API data requested successfully.")

            json_data = response.json()
            release_items = json_data.get("data", [])

            print(f"Found {len(release_items)} upcoming releases in API response.")

            if not release_items:
                print("No releases found in the API response.")
                return

            new_releases_found = 0
            for item in release_items:
                attributes = item.get("attributes", {})
                name = attributes.get("name")
                image_url = attributes.get("image_url")
                date_iso_str = attributes.get("release_date")

                if name_element and date_element and image_element:
                    name = name_element.text.strip()

                    # --- NEW LOGIC: Extract the brand ---
                    # We'll assume the first word of the name is the brand.
                    brand = name.split(' ')[0]
                    try:
                        release_date = datetime.fromisoformat(date_iso_str.replace("Z", "+00:00")).date()
                        existing_release = Release.query.filter_by(name=name, release_date=release_date).first()
                        if not existing_release:
                            new_release = Release(
                                brand=brand,
                                name=name,
                                release_date=release_date,
                                retail_price=attributes.get("retail_price", "N/A"),
                                image_url=image_url
                            )
                            db.session.add(new_release)
                            new_releases_found += 1
                            print(f"  -> ADDING: {name} ({release_date})")
                    except (ValueError, TypeError):
                        print(f"Could not parse date: '{date_iso_str}' for {name}")
                        continue

            if new_releases_found > 0:
                db.session.commit()
                print(f"SUCCESS: Added {new_releases_found} new releases to the database.")
            else:
                print("No new releases found to add (they may already be in the database).")

        except requests.exceptions.RequestException as e:
            print(f"Error during API request: {e}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

if __name__ == '__main__':
    scrape_drop_date_api()