"""Add Release model

Revision ID: 51c81389f093
Revises: ada055b84a20
Create Date: 2025-06-16 19:33:43.091649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c81389f093'
down_revision = 'ada055b84a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('retail_price', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_release_date'), ['release_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_release_date'))

    op.drop_table('release')
    # ### end Alembic commands ###
