"""Add is_email_confirmed to User model updated

Revision ID: 75e26b122aab
Revises: 79d59368c4bd
Create Date: 2025-05-30 23:14:58.118797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e26b122aab'
down_revision = '79d59368c4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_confirmed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_email_confirmed')

    # ### end Alembic commands ###
