"""Add is_email_confirmed to User model

Revision ID: 79d59368c4bd
Revises: aa404db0c8b4
Create Date: 2025-05-30 22:59:21.044251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d59368c4bd'
down_revision = 'aa404db0c8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
