"""Add brand column to Release model

Revision ID: 872be984ab17
Revises: ac72fc0c6940
Create Date: 2025-06-19 14:21:32.447247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872be984ab17'
down_revision = 'ac72fc0c6940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_release_brand'), ['brand'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_brand'))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
