"""Add pending_email for email change verification

Revision ID: aa404db0c8b4
Revises: f52ba62dd3b7
Create Date: 2025-05-28 18:23:14.728372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa404db0c8b4'
down_revision = 'f52ba62dd3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_pending_email', ['pending_email']) # <-- CHANGED None to 'uq_user_pending_email'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
