"""Add in_rotation status to Sneaker model

Revision ID: ada055b84a20
Revises: 75e26b122aab
Create Date: 2025-06-06 16:09:43.946984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada055b84a20'
down_revision = '75e26b122aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_rotation', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_sneaker_in_rotation'), ['in_rotation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sneaker_in_rotation'))
        batch_op.drop_column('in_rotation')

    # ### end Alembic commands ###
