"""Add SneakerDB model for master sneaker list

Revision ID: de1c01809750
Revises: 872be984ab17
Create Date: 2025-07-31 22:51:04.449676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1c01809750'
down_revision = '872be984ab17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('colorway', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sneaker_db', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sneaker_db_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_sneaker_db_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sneaker_db_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker_db', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sneaker_db_sku'))
        batch_op.drop_index(batch_op.f('ix_sneaker_db_name'))
        batch_op.drop_index(batch_op.f('ix_sneaker_db_brand'))

    op.drop_table('sneaker_db')
    # ### end Alembic commands ###
