"""Add marketing_opt_in to User model

Revision ID: f52ba62dd3b7
Revises: 42bc904bb081
Create Date: 2025-05-28 17:23:45.760708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52ba62dd3b7'
down_revision = '42bc904bb081'
branch_labels = None
depends_on = None


def upgrade():
    false_default = sa.false() if op.get_bind().dialect.name == 'postgresql' else '0'
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # This line (and any other batch_op commands) MUST be indented
        batch_op.add_column(
            sa.Column('marketing_opt_in', sa.Boolean(), nullable=False, server_default=false_default)
        )
        # If there were other operations in this batch, like creating a unique constraint,
        # they would also be indented here. For example:
        # batch_op.create_unique_constraint('uq_user_email', ['email']) # From a previous fix, if it was in THIS script

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('marketing_opt_in')

    # ### end Alembic commands ###
